### ISSUE TITLE
CreativeTab Crash: unkown error

### ISSUE THREAD

**Issue by BestOwl** [GoodTimeStudio/GoodTime-Industrial#4]

**Comment by liach** [comment]
Umm.. Any crash report?

**Comment by BestOwl** [comment]
net.minecraft.util.ReportedException: Rendering item
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1168) ~[EntityRenderer.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1057) ~[Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:951) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:164) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
    at GradleStart.main(Unknown Source) [start/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.getItemDamage(ItemStack.java:265) ~[ItemStack.class:?]
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:419) ~[RenderItem.class:?]
    at net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:585) ~[RenderItem.class:?]
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:968) ~[GuiContainerCreative.class:?]
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawGuiContainerBackgroundLayer(GuiContainerCreative.java:795) ~[GuiContainerCreative.class:?]
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:93) ~[GuiContainer.class:?]
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:44) ~[InventoryEffectRenderer.class:?]
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:673) ~[GuiContainerCreative.class:?]
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137) ~[EntityRenderer.class:?]
    ... 16 more
[13:13:20] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 15-3-23 下午1:13
Description: Rendering item

java.lang.NullPointerException: Rendering item
    at net.minecraft.item.ItemStack.getItemDamage(ItemStack.java:265)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:419)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:585)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:968)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawGuiContainerBackgroundLayer(GuiContainerCreative.java:795)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:93)
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:44)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:673)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1057)
    at net.minecraft.client.Minecraft.run(Minecraft.java:951)
    at net.minecraft.client.main.Main.main(Main.java:164)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
    at GradleStart.main(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.getItemDamage(ItemStack.java:265)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:419)

-- Item being rendered --
Details:
    Item Type: null
    Item Aux: ~~ERROR~~ NullPointerException: null
    Item NBT: null
    Item Foil: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:585)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:968)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawGuiContainerBackgroundLayer(GuiContainerCreative.java:795)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:93)
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:44)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:673)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (306, 9). Absolute: (612, 461)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['_JAVA7'/409, l='MpServer', x=51.43, y=65.62, z=282.15]]
    Chunk stats: MultiplayerChunkCache: 586, 586
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (52,64,283), Chunk: (at 4,4,11 in 3,17; contains blocks 48,0,272 to 63,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 18276 game time, 18276 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 109 total; [EntityChicken['Chicken'/256, l='MpServer', x=88.38, y=68.00, z=262.44], EntityChicken['Chicken'/257, l='MpServer', x=84.53, y=69.00, z=256.63], EntitySkeleton['Skeleton'/258, l='MpServer', x=83.84, y=58.00, z=321.56], EntityZombie['Zombie'/259, l='MpServer', x=85.28, y=38.00, z=331.69], EntityZombie['Zombie'/260, l='MpServer', x=81.88, y=38.00, z=331.41], EntityBat['Bat'/261, l='MpServer', x=93.75, y=63.10, z=320.66], EntitySkeleton['Skeleton'/262, l='MpServer', x=84.71, y=55.00, z=329.46], EntityZombie['Zombie'/275, l='MpServer', x=107.38, y=20.00, z=236.94], EntityCreeper['Creeper'/276, l='MpServer', x=107.66, y=65.00, z=226.00], EntityChicken['Chicken'/277, l='MpServer', x=97.34, y=62.37, z=242.19], EntityPig['Pig'/278, l='MpServer', x=108.63, y=64.00, z=240.19], EntityCow['Cow'/279, l='MpServer', x=96.41, y=69.00, z=303.63], EntityZombie['Zombie'/280, l='MpServer', x=99.75, y=59.00, z=317.66], EntityZombie['Zombie'/281, l='MpServer', x=100.69, y=59.00, z=316.59], EntityZombie['Zombie'/282, l='MpServer', x=100.03, y=62.00, z=322.41], EntitySheep['Sheep'/284, l='MpServer', x=98.94, y=64.00, z=359.97], EntitySheep['Sheep'/285, l='MpServer', x=105.38, y=64.00, z=361.19], EntityZombie['Zombie'/295, l='MpServer', x=121.00, y=23.00, z=249.34], EntityCow['Cow'/296, l='MpServer', x=117.94, y=63.00, z=246.81], EntitySpider['Spider'/297, l='MpServer', x=114.28, y=63.00, z=240.50], EntityCow['Cow'/298, l='MpServer', x=112.34, y=65.00, z=298.81], EntityCow['Cow'/299, l='MpServer', x=117.25, y=65.00, z=290.50], EntitySkeleton['Skeleton'/300, l='MpServer', x=116.75, y=66.00, z=303.25], EntityCow['Cow'/301, l='MpServer', x=111.31, y=65.00, z=297.53], EntityCow['Cow'/309, l='MpServer', x=125.06, y=63.00, z=243.03], EntityCreeper['Creeper'/310, l='MpServer', x=130.31, y=63.00, z=242.03], EntityCreeper['Creeper'/311, l='MpServer', x=130.41, y=63.00, z=250.50], EntityBat['Bat'/107, l='MpServer', x=-18.41, y=42.10, z=236.63], EntityZombie['Zombie'/108, l='MpServer', x=-17.13, y=66.00, z=236.16], EntityCow['Cow'/109, l='MpServer', x=-26.88, y=65.00, z=249.13], EntitySheep['Sheep'/111, l='MpServer', x=-24.38, y=69.00, z=262.13], EntityCow['Cow'/112, l='MpServer', x=-20.84, y=68.00, z=263.03], EntityCreeper['Creeper'/113, l='MpServer', x=-24.03, y=71.00, z=314.31], EntitySkeleton['Skeleton'/117, l='MpServer', x=-1.50, y=58.00, z=223.28], EntitySkeleton['Skeleton'/118, l='MpServer', x=-21.16, y=68.00, z=226.50], EntitySkeleton['Skeleton'/119, l='MpServer', x=-10.50, y=68.00, z=213.50], EntityCow['Cow'/120, l='MpServer', x=-3.75, y=70.00, z=288.50], EntityCreeper['Creeper'/121, l='MpServer', x=-17.00, y=71.00, z=309.44], EntityZombie['Zombie'/122, l='MpServer', x=-12.38, y=16.00, z=326.13], EntitySkeleton['Skeleton'/123, l='MpServer', x=-11.06, y=16.00, z=323.50], EntityPig['Pig'/124, l='MpServer', x=-6.47, y=72.00, z=330.50], EntityPig['Pig'/125, l='MpServer', x=-1.56, y=73.00, z=341.56], EntityZombie['Zombie'/140, l='MpServer', x=2.70, y=32.83, z=219.70], EntityPig['Pig'/141, l='MpServer', x=3.50, y=68.00, z=223.13], EntitySheep['Sheep'/142, l='MpServer', x=8.50, y=67.00, z=217.50], EntityPig['Pig'/143, l='MpServer', x=0.31, y=68.00, z=218.50], EntityBat['Bat'/144, l='MpServer', x=-2.89, y=15.23, z=223.31], EntityZombie['Zombie'/145, l='MpServer', x=8.00, y=40.00, z=237.44], EntitySkeleton['Skeleton'/146, l='MpServer', x=14.78, y=64.00, z=234.63], EntityCow['Cow'/147, l='MpServer', x=11.56, y=65.00, z=273.89], EntitySpider['Spider'/148, l='MpServer', x=13.63, y=38.00, z=297.88], EntityZombie['Zombie'/149, l='MpServer', x=14.94, y=14.00, z=321.50], EntityBat['Bat'/150, l='MpServer', x=19.71, y=25.00, z=323.33], EntityPig['Pig'/151, l='MpServer', x=13.93, y=68.00, z=357.60], EntityClientPlayerMP['_JAVA7'/409, l='MpServer', x=51.43, y=65.62, z=282.15], EntitySkeleton['Skeleton'/165, l='MpServer', x=13.69, y=38.00, z=226.22], EntitySheep['Sheep'/166, l='MpServer', x=28.53, y=64.00, z=209.97], EntityCow['Cow'/167, l='MpServer', x=29.28, y=64.00, z=208.56], EntitySheep['Sheep'/168, l='MpServer', x=28.81, y=64.00, z=211.88], EntityPig['Pig'/169, l='MpServer', x=12.25, y=64.00, z=238.38], EntityPig['Pig'/170, l='MpServer', x=21.38, y=64.00, z=236.81], EntityCreeper['Creeper'/171, l='MpServer', x=30.38, y=22.00, z=248.09], EntitySpider['Spider'/172, l='MpServer', x=30.92, y=63.00, z=245.19], EntityCreeper['Creeper'/173, l='MpServer', x=23.06, y=33.00, z=298.63], EntitySheep['Sheep'/174, l='MpServer', x=31.19, y=69.00, z=299.19], EntitySkeleton['Skeleton'/175, l='MpServer', x=24.13, y=38.00, z=305.63], EntitySkeleton['Skeleton'/176, l='MpServer', x=21.09, y=28.00, z=327.53], EntityZombie['Zombie'/177, l='MpServer', x=28.45, y=74.00, z=326.99], EntitySheep['Sheep'/182, l='MpServer', x=47.16, y=66.00, z=205.75], EntityCow['Cow'/183, l='MpServer', x=43.84, y=65.00, z=216.06], EntityCow['Cow'/184, l='MpServer', x=35.13, y=65.00, z=215.13], EntityChicken['Chicken'/185, l='MpServer', x=39.63, y=65.00, z=220.59], EntitySkeleton['Skeleton'/186, l='MpServer', x=42.13, y=65.00, z=220.72], EntitySkeleton['Skeleton'/187, l='MpServer', x=41.06, y=64.00, z=230.47], EntityBat['Bat'/188, l='MpServer', x=43.25, y=61.10, z=269.72], EntityBat['Bat'/189, l='MpServer', x=40.75, y=61.10, z=269.75], EntityCreeper['Creeper'/190, l='MpServer', x=39.66, y=58.00, z=268.28], EntityCow['Cow'/191, l='MpServer', x=36.72, y=64.00, z=264.19], EntityZombie['Zombie'/192, l='MpServer', x=38.13, y=33.00, z=308.50], EntityCreeper['Creeper'/193, l='MpServer', x=41.28, y=50.00, z=320.31], EntitySheep['Sheep'/194, l='MpServer', x=36.78, y=73.00, z=324.91], EntitySheep['Sheep'/195, l='MpServer', x=43.19, y=64.00, z=333.25], EntitySkeleton['Skeleton'/196, l='MpServer', x=34.31, y=51.05, z=361.75], EntitySkeleton['Skeleton'/197, l='MpServer', x=38.09, y=51.04, z=359.59], EntitySheep['Sheep'/211, l='MpServer', x=57.09, y=67.00, z=212.09], EntitySkeleton['Skeleton'/212, l='MpServer', x=50.94, y=57.00, z=234.44], EntityChicken['Chicken'/213, l='MpServer', x=55.63, y=65.00, z=229.44], EntityChicken['Chicken'/214, l='MpServer', x=48.53, y=57.00, z=254.66], EntityChicken['Chicken'/215, l='MpServer', x=51.44, y=64.00, z=244.56], EntityZombie['Zombie'/216, l='MpServer', x=56.47, y=18.00, z=310.97], EntityBat['Bat'/217, l='MpServer', x=60.10, y=32.88, z=306.10], EntityCow['Cow'/218, l='MpServer', x=53.81, y=64.00, z=312.19], EntitySkeleton['Skeleton'/219, l='MpServer', x=69.16, y=15.00, z=317.75], EntityBat['Bat'/220, l='MpServer', x=65.22, y=32.12, z=323.58], EntityPig['Pig'/231, l='MpServer', x=78.81, y=67.00, z=216.13], EntityPig['Pig'/232, l='MpServer', x=73.44, y=64.00, z=233.72], EntityPig['Pig'/233, l='MpServer', x=70.84, y=66.00, z=225.03], EntityBat['Bat'/234, l='MpServer', x=68.72, y=40.10, z=274.41], EntitySheep['Sheep'/235, l='MpServer', x=74.06, y=64.00, z=296.06], EntityZombie['Zombie'/236, l='MpServer', x=69.91, y=17.00, z=315.50], EntitySkeleton['Skeleton'/237, l='MpServer', x=67.88, y=15.00, z=319.50], EntityZombie['Zombie'/238, l='MpServer', x=69.06, y=16.00, z=321.47], EntityWitch['Witch'/239, l='MpServer', x=65.03, y=17.00, z=322.66], EntitySkeleton['Skeleton'/240, l='MpServer', x=63.91, y=39.00, z=327.50], EntitySpider['Spider'/241, l='MpServer', x=71.81, y=37.95, z=330.28], EntitySkeleton['Skeleton'/252, l='MpServer', x=86.44, y=32.00, z=206.22], EntityEnderman['Enderman'/253, l='MpServer', x=88.50, y=20.00, z=220.44], EntitySkeleton['Skeleton'/254, l='MpServer', x=83.91, y=20.00, z=232.50], EntityZombie['Zombie'/255, l='MpServer', x=89.59, y=20.00, z=258.00]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:415)
    at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2556)
    at net.minecraft.client.Minecraft.run(Minecraft.java:972)
    at net.minecraft.client.main.Main.main(Main.java:164)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
    at GradleStart.main(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by liach** [comment]
We just need a npe check...

**Comment by BestOwl** [comment]
fixed

**Comment by liach** [comment]
This time "really" fixed.
